#-----------------------------------------------------------------------#
# File name        : model-selector-time-series-r
# Project          :
# PI               : Nathan Armani PhD, M.Ed.
#                    Assistant Professor of Biomechanics
#                    York College of Pennsylvania
#                    narmani@ycp.edu
#-----------------------------------------------------------------------#
# Purpose          : Time series analysis 
#-----------------------------------------------------------------------#
# Created by       : Nathan Armani
# Created date     : May. 12, 2025
#-----------------------------------------------------------------------#
#⚠️ Disclaimer
# The results and forecasts generated by this tool are intended for educational 
# and exploratory purposes only. 
# While the models used (linear, quadratic, and exponential regression) are valid 
# statistical techniques, # they make assumptions that may not fully capture 
# the complexities or external influences affecting real-world salary trends.
# This tool does not account for economic conditions, collective bargaining agreements, 
# market dynamics, or domain-specific variables that may influence salaries over time. 
# Forecasts should not be interpreted as precise predictions or used for financial, 
# strategic, or investment decisions without further domain-specific validation and analysis.
# Use this script responsibly and supplement it with expert judgment or advanced time series techniques 
# (e.g., ARIMA, machine learning models) for more robust insights.
#-----------------------------------------------------------------------#

# Load required libraries
library(readxl)
library(ggplot2)
library(tidyr)
library(dplyr)

# Set seed and options
set.seed(123)
options(warn = -1, 
        scipen = 999, 
        error = traceback)

rm(list = ls())
cat("\014")

# Ask for plotting style
plot_choice <- tolower(readline(prompt = "Would you like separate plots for each model? (yes/no): "))

# Ask for forecasting
do_forecast <- tolower(readline(prompt = "Would you like to perform forecasting? (yes/no): "))

# Get forecast range if needed
if (do_forecast == "yes") {
  forecast_start <- as.integer(readline(prompt = "Enter start year for forecast (e.g., 2019): "))
  forecast_end <- as.integer(readline(prompt = "Enter end year for forecast (e.g., 2022): "))
} else {
  forecast_start <- NA
  forecast_end <- NA
}

# Load data
MyData <- read_excel("C:/Users/natha/Desktop/Stat/Book1.xlsx", 
                     sheet = "Sheet5")
MyData$IV <- MyData$Year
MyData$DV <- MyData$`Salary (Millions)`

# Axis and title
XMIN <- min(MyData$IV)
XMAX <- max(MyData$IV)
XINDENT <- 2
YMIN <- 0
YMAX <- round(max(MyData$DV), digits = 0)
YINDENT <- round((max(MyData$DV) - 0)/10, digits = 1)
DV_Title <- "Salary"
IV_Title <- "Year"
Graph_Title <- paste0(DV_Title, " by ", IV_Title)

# Recode year
x <- 0:(nrow(MyData)-1)
data <- data.frame(IV = MyData$IV, x = x, DV = MyData$DV)

# Fit models
Linear_Model <- lm(DV ~ x, data = data)
Quad_Model <- lm(DV ~ poly(x, 2, raw = TRUE), data = data)
Exp_Model <- lm(log(DV) ~ x, data = data)

# Forecasting
if (do_forecast == "yes") {
  min_x <- forecast_start - min(MyData$IV)
  max_x <- forecast_end - min(MyData$IV)
  forecast_years <- data.frame(x = min_x:max_x)
  
  linear_forecast <- predict(Linear_Model, newdata = forecast_years)
  quad_forecast <- predict(Quad_Model, newdata = forecast_years)
  exp_forecast <- exp(predict(Exp_Model, newdata = forecast_years))
  
  forecast_table <- data.frame(Year = forecast_start:forecast_end,
                               Linear = round(linear_forecast, 3),
                               Quadratic = round(quad_forecast, 3),
                               Exponential = round(exp_forecast, 3))
}

# Model coefficients and R²
int_lin <- coef(Linear_Model)[1]
slope_lin <- coef(Linear_Model)[2]
r2_lin <- summary(Linear_Model)$r.squared

int_quad <- coef(Quad_Model)[1]
b1_quad <- coef(Quad_Model)[2]
b2_quad <- coef(Quad_Model)[3]
r2_quad <- summary(Quad_Model)$r.squared

int_exp <- coef(Exp_Model)[1]
slope_exp <- coef(Exp_Model)[2]
r2_exp <- summary(Exp_Model)$r.squared

Results <- data.frame(Model = c("Linear", "Quadratic", "Exponential"),
                      Intercept = c(round(int_lin, 2), round(int_quad, 2), round(int_exp, 2)),
                      IV_Coeff_1 = c(round(slope_lin, 4), round(b1_quad, 4), round(slope_exp, 4)),
                      IV_Coeff_2 = c(NA, round(b2_quad, 4), NA),
                      R_squared = c(round(r2_lin, 4), round(r2_quad, 4), round(r2_exp, 4)))

# AIC/BIC
AIC <- AIC(Linear_Model, Exp_Model, Quad_Model)
BIC <- BIC(Linear_Model, Exp_Model, Quad_Model)

# Differences
MyData <- MyData %>%
  arrange(IV) %>%
  mutate(First_Diff = DV - lag(DV),
         Second_Diff = First_Diff - lag(First_Diff),
         Perc_Change = (DV - lag(DV)) / lag(DV) * 100)

# ---------- Plot Section ----------
if (plot_choice == "yes") {
  # Refit on original IV
  Linear_Model_IV <- lm(DV ~ IV, data = MyData)
  MyData$Linear <- predict(Linear_Model_IV)
  
  Quad_Model_IV <- lm(DV ~ poly(IV, 2, raw = TRUE), data = MyData)
  MyData$Quadratic <- predict(Quad_Model_IV)
  
  Exp_Model_IV <- lm(log(DV) ~ IV, data = MyData)
  MyData$Exponential <- exp(predict(Exp_Model_IV))
  
  # Equation strings
  eq_lin <- paste0("y = ", round(coef(Linear_Model_IV)[1], 2), 
                   " + ", round(coef(Linear_Model_IV)[2], 2), "x\n",
                   "R² = ", round(summary(Linear_Model_IV)$r.squared, 3))
  
  eq_quad <- paste0("y = ", round(coef(Quad_Model_IV)[1], 2), 
                    " + ", round(coef(Quad_Model_IV)[2], 2), "x", 
                    " + ", round(coef(Quad_Model_IV)[3], 2), "x²\n",
                    "R² = ", round(summary(Quad_Model_IV)$r.squared, 3))
  
  a <- round(exp(coef(Exp_Model_IV)[1]), 4)
  b <- round(exp(coef(Exp_Model_IV)[2]), 4)
  eq_exp <- paste0("y = ", a, " × ", b, "^x\n",
                   "R² = ", round(summary(Exp_Model_IV)$r.squared, 3))
  
  # Original Data Plot
  print(
    ggplot(MyData, aes(x = IV, y = DV)) +
      geom_point(color = "#4B0082", size = 2) +
      scale_x_continuous(limits = c(XMIN, XMAX), breaks = seq(XMIN, XMAX, by = XINDENT)) +
      scale_y_continuous(limits = c(YMIN, YMAX), breaks = seq(YMIN, YMAX, by = YINDENT)) +
      labs(title = Graph_Title, x = IV_Title, y = DV_Title) +
      theme_classic(base_size = 20) +
      theme(plot.title = element_text(hjust = 0.5),
            axis.title = element_text(size = 16, face = "bold"),
            axis.text.x = element_text(colour = "black", face = "bold", size = 14, angle = 0, hjust = 0.5),
            axis.text.y = element_text(colour = "black", face = "bold", size = 14)))
  
  # Linear
  print(
    ggplot(MyData, aes(x = IV, y = DV)) +
      geom_point(color = "#4B0082", size = 2) +
      geom_line(aes(y = Linear), color = "#800000", size = 1.2) +
      annotate("text", x = XMIN + 1, y = YMAX - 0.5, label = eq_lin, hjust = 0, size = 5) +
      labs(title = "Linear Trend Forecasting", x = IV_Title, y = DV_Title) +
      theme_classic(base_size = 20) +
      scale_x_continuous(limits = c(XMIN, XMAX),
                         breaks = seq(XMIN, XMAX, by = XINDENT)) +
      scale_y_continuous(limits = c(YMIN, YMAX),
                         breaks = seq(YMIN, YMAX, by = YINDENT)) +
      theme(plot.title = element_text(hjust = 0.5),
            axis.title = element_text(size = 16, 
                                      face = "bold"),
            axis.text.x = element_text(colour = "black", 
                                       face = "bold", 
                                       size = 14, 
                                       angle = 0, 
                                       hjust = 0.5),
            axis.text.y = element_text(colour = "black", 
                                       face = "bold", 
                                       size = 14)))
  
  # Quadratic
  print(
    ggplot(MyData, aes(x = IV, y = DV)) +
      geom_point(color = "#4B0082", size = 2) +
      geom_line(aes(y = Quadratic), color = "#B8860B", size = 1.2) +
      annotate("text", x = XMIN + 1, y = YMAX - 0.5, label = eq_quad, hjust = 0, size = 5) +
      labs(title = "Quadratic Trend Forecasting", x = IV_Title, y = DV_Title) +
      theme_classic(base_size = 20) +
      scale_x_continuous(limits = c(XMIN, XMAX),
                         breaks = seq(XMIN, XMAX, by = XINDENT)) +
      scale_y_continuous(limits = c(YMIN, YMAX),
                         breaks = seq(YMIN, YMAX, by = YINDENT)) +
      theme(plot.title = element_text(hjust = 0.5),
            axis.title = element_text(size = 16, 
                                      face = "bold"),
            axis.text.x = element_text(colour = "black", 
                                       face = "bold", 
                                       size = 14, 
                                       angle = 0, 
                                       hjust = 0.5),
            axis.text.y = element_text(colour = "black", 
                                       face = "bold", 
                                       size = 14)))
  
  # Exponential
  print(
    ggplot(MyData, aes(x = IV, y = DV)) +
      geom_point(color = "#4B0082", size = 2) +
      geom_line(aes(y = Exponential), color = "#556B2F", size = 1.2) +
      annotate("text", x = XMIN + 1, y = YMAX - 0.5, label = eq_exp, hjust = 0, size = 5) +
      labs(title = "Exponential Trend Forecasting", x = IV_Title, y = DV_Title) +
      theme_classic(base_size = 20) +
      scale_x_continuous(limits = c(XMIN, XMAX),
                         breaks = seq(XMIN, XMAX, by = XINDENT)) +
      scale_y_continuous(limits = c(YMIN, YMAX),
                         breaks = seq(YMIN, YMAX, by = YINDENT)) +
      theme(plot.title = element_text(hjust = 0.5),
            axis.title = element_text(size = 16, 
                                      face = "bold"),
            axis.text.x = element_text(colour = "black", 
                                       face = "bold", 
                                       size = 14, 
                                       angle = 0, 
                                       hjust = 0.5),
            axis.text.y = element_text(colour = "black", 
                                       face = "bold", 
                                       size = 14)))
  
} else {
  # Combined plot
  max_x_plot <- 18
  x_vals <- data.frame(x = 0:max_x_plot)
  x_vals$Linear <- predict(Linear_Model, newdata = x_vals)
  x_vals$Quadratic <- predict(Quad_Model, newdata = x_vals)
  x_vals$Exponential <- exp(predict(Exp_Model, newdata = x_vals))
  x_vals$IV <- min(MyData$IV) + x_vals$x
  
  long_preds <- x_vals %>%
    select(IV, Linear, Quadratic, Exponential) %>%
    pivot_longer(cols = -IV, names_to = "Model", values_to = "Predicted_Salary")
  
  print(ggplot(data, aes(x = IV, y = DV)) +
          geom_point(size = 3, color = "black") +
          geom_line(data = long_preds, aes(x = IV, y = Predicted_Salary, color = Model, linetype = Model), size = 1) +
          labs(title = "MLB Average Salary Forecasts", y = "Salary (Millions)", x = "Year", color = "Model", linetype = "Model") +
          scale_x_continuous(limits = c(XMIN, XMAX), breaks = seq(XMIN, XMAX, by = XINDENT)) +
          scale_y_continuous(limits = c(YMIN, YMAX), breaks = seq(YMIN, YMAX, by = YINDENT)) +
          theme_classic(base_size = 20) +
          theme(plot.title = element_text(hjust = 0.5),
                axis.title = element_text(size = 16, 
                                          face = "bold"),
                axis.text.x = element_text(colour = "black", 
                                           face = "bold", 
                                           size = 14, 
                                           angle = 0, 
                                           hjust = 0.5),
                axis.text.y = element_text(colour = "black", 
                                           face = "bold", 
                                           size = 14)))
}

if (do_forecast == "yes") {
  long_preds <- forecast_table %>%
    pivot_longer(cols = -Year, names_to = "Model", values_to = "Predicted_Salary") %>%
    rename(IV = Year)  # Rename to match your existing plotting code
  
  XMINP <- min(long_preds$IV)
  XMAXP <- max(long_preds$IV)
  YMINP <- 0
  YMAXP <- max(long_preds$Predicted_Salary)
  
  # Plotting forecasted data using your full styling
  print(ggplot() +
          geom_line(data = long_preds, aes(x = IV, y = Predicted_Salary, color = Model, linetype = Model), size = 1) +
          geom_point(data = long_preds, aes(x = IV, y = Predicted_Salary, color = Model), size = 3) +
          labs(title = "MLB Average Salary Forecasts",
            y = "Salary (Millions)",
            x = "Year",
            color = "Model",
          linetype = "Model") +
          scale_x_continuous(limits = c(XMINP, XMAXP), breaks = seq(XMINP, XMAXP, by = XINDENT)) +
          scale_y_continuous(limits = c(YMINP, YMAXP), breaks = seq(YMINP, YMAXP, by = YINDENT)) +
          theme_classic(base_size = 20) +
          theme(plot.title = element_text(hjust = 0.5),
                axis.title = element_text(size = 16, face = "bold"),
                axis.text.x = element_text(colour = "black", face = "bold", size = 14, angle = 0, hjust = 0.5),
                axis.text.y = element_text(colour = "black", face = "bold", size = 14)))
  
}

# ---------- Recommendation Section ----------
# Extract values
aic_vals <- AIC$AIC
bic_vals <- BIC$BIC
r2_vals <- c(r2_lin, r2_quad, r2_exp)

# Find best by each metric
best_aic <- AIC$df[which.min(aic_vals)]
best_bic <- BIC$df[which.min(bic_vals)]
best_r2 <- c("Linear", "Quadratic", "Exponential")[which.max(r2_vals)]

# Count votes
votes <- c(Linear = 0, Quadratic = 0, Exponential = 0)
votes[best_aic] <- votes[best_aic] + 1
votes[best_bic] <- votes[best_bic] + 1
votes[best_r2] <- votes[best_r2] + 1

# Choose model with majority votes (or use R² as tie-breaker)
recommended_model <- names(which.max(votes))

# Final summary table
Model_Comparison <- data.frame(
  Metric = c("Lowest AIC", 
             "Lowest BIC", 
             "Highest R²", 
             "Recommended Model"),
  Model = c(best_aic, 
            best_bic, 
            best_r2, 
            recommended_model))

# ---------- Final Outputs ----------
cat("\014")
if (do_forecast == "yes") print(forecast_table)
print(Results)
print(AIC)
print(BIC)
cat("\nMODEL SELECTION SUMMARY:\n")
print(Model_Comparison, row.names = FALSE)
